Movie326/urls.py
from django.contrib import admin
from django.urls import path, include
from catalog import views
from catalog.views import *
from django.shortcuts import redirect
from django.contrib.auth import views as auth_views
from django.urls import path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='home'),
    path('kino/all/', kinolist.as_view(), name='allkino'),
    # path('kino/<int:pk>/', kinodetail.as_view(), name='info'),
    path('kino/<int:pk>/', kinodetail, name='info'),
    path('director/all/', directorlist.as_view(), name='alldirector'),
    path('director/<int:pk>/', directordetail.as_view(), name='infodirector'),
    path('actor/all/', actorlist.as_view(), name='allactor'),
    path('actor/<int:pk>/', actordetail.as_view(), name='infoactor'),
    path('user/', include('django.contrib.auth.urls')),
    path('accounts/profile/', lambda request: index(request)),
    path('user/reg/', reg, name='registration'),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('podpiska/<int:userid>/', topodpiska, name='podpiska'),
    path('search/', search_films, name='search'),

    # path('podpiska/plusbalance/', plusbalance, name='plusbalance'),
]

catalog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser


# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=20, verbose_name='Жанр')

    def __str__(self):
        return self.name

class Director(models.Model):
    name = models.CharField(max_length=50, verbose_name='Имя/Фамилия')
    info = models.URLField(blank=True)
    data = models.DateField(verbose_name='Дата рождения: ', blank=True, null=True)
    filmcount = models.IntegerField(verbose_name='Всего фильмов: ', blank=True, null=True)
    best = models.TextField(max_length=5000, verbose_name='Лучшие фильмы: ', blank=True)
    image = models.URLField(verbose_name='Фото', blank=True, null=True)
    def __str__(self):
        return self.name
    def getAbsUrl(self):
        return reverse('infodirector', args=[self.id])

class Actor(models.Model):
    name = models.CharField(max_length=50, verbose_name='Имя/Фамилия')
    info = models.URLField(blank=True)
    data = models.DateField(verbose_name='Дата рождения: ', blank=True, null=True)
    filmcount = models.IntegerField(verbose_name='Всего фильмов: ', blank=True, null=True)
    image = models.URLField(verbose_name='Фото', blank=True, null=True)
    best = models.TextField(max_length=5000, verbose_name='Лучшие фильмы: ', blank=True, null=True)
    def __str__(self):
        return self.name
    def getAbsUrl(self):
        return reverse('infoactor', args=[self.id])

class Country(models.Model):
    name = models.CharField(max_length=30, verbose_name='Страна')

    def __str__(self):
        return self.name

class Podpiska(models.Model):
    VIBOR = (('free', 'БЕСПЛАТНАЯ'), ('based', 'БАЗОВАЯ'), ('super', 'ПРЕМИУМ'))
    level = models.CharField(max_length=20, choices=VIBOR, verbose_name='Подписка')

    def __str__(self):
        return self.get_level_display()

class Kino(models.Model):
    title = models.CharField(max_length=100, verbose_name='Название')
    genre = models.ForeignKey(Genre, on_delete=models.SET_NULL, null=True)
    director = models.ForeignKey(Director, on_delete=models.SET_NULL, null=True)
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True)
    year = models.IntegerField(verbose_name='Год выхода')
    actors = models.ManyToManyField(Actor, verbose_name='Актеры')
    podpiska = models.ForeignKey(Podpiska, on_delete=models.SET_NULL, null=True)
    image = models.URLField(verbose_name='Изображение', blank=True)
    poster = models.URLField(verbose_name='Постер', blank=True)
    opisanie = models.TextField(max_length=2000, verbose_name='Описание', blank=True)
    trailer_url = models.URLField(verbose_name='Трейлер', null=True, unique=True, blank=True)


    def __str__(self):
        return self.title

    def displayAct(self):
        res = ''
        for one in self.actors.all():
            res += one.name + ' '
            return res

    displayAct.short_description = 'Актеры'

    def getAbsUrl(self):
        return reverse('info', args=[self.id])


class ProfiUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    podpiska = models.ForeignKey(Podpiska, on_delete=models.SET_NULL, null=True)
    balance = models.IntegerField(default=10)

    # def __str__(self):
    #     return self.user.username

class Comment(models.Model):
    # name = models.CharField(max_length=50)
    body = models.TextField(verbose_name='Напишите комментарий')
    timedata = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=False)
    kino = models.ForeignKey(Kino, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.body

class Video(models.Model):
    likes = models.ManyToManyField(User, blank=True, related_name='likes')
    dislikes = models.ManyToManyField(User, blank=True, related_name='dislikes')

catalog/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm
from .models import *

class SignUp(UserCreationForm):
    username = forms.CharField(label='Логин', help_text='',
                               widget=forms.TextInput(attrs={"placeholder": "введите логин"}))
    password1 = forms.CharField(
        label='Пароль',
        help_text='',
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password", 'placeholder': 'введите пароль'})
    )
    password2 = forms.CharField(
        label='Подтверждение',
        help_text='',
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password", 'placeholder': 'повторите пароль'})
    )
    email = forms.EmailField(
        label='Почта',
        widget=forms.TextInput(attrs={'placeholder': 'qwe@mail.ru'})
    )
    first_name = forms.CharField(label='Имя', max_length=30, required=False, widget=forms.TextInput(attrs={'placeholder': 'введите имя'}))
    last_name = forms.CharField(label='Фамилия', max_length=30, required=False, widget=forms.TextInput(attrs={'placeholder': 'введите фамилию'}))


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']

catalog/views.py
from django.shortcuts import render
from .forms import SignUp
from .models import *
import requests
from django.http import HttpResponse
from django.views import generic
import os
import uuid
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from .forms import *
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, views


def index(req):
    items = Kino.objects.all()
    items2 = Kino.objects.filter(podpiska__level='free')
    data = {'k1': items.count(), 'k2': items2.count()}
    return render(req, 'index.html', data)


class kinolist(generic.ListView):
    model = Kino
    paginate_by = 5


# class kinodetail(generic.DetailView):
#     model = Kino

def proverka(newcom):
    blacklist = ['жопа']
    spisok = newcom.body.split()
    active = True
    for one in spisok:
        if one in blacklist:
            newcom.delete()
            active = False
    if active:
        newcom.active = True
        newcom.save()


def kinodetail(req, pk):
    film = Kino.objects.get(id=pk)
    comments = film.comment_set.filter(active=True)
    forma = CommentForm()
    if req.method == 'POST':
        form = CommentForm(req.POST)
        if form.is_valid():
            newcom = form.save(commit=False)
            newcom.kino = film
            newcom.user = req.user
            proverka(newcom)
            form.save()
            return redirect('info', pk=pk)
    else:
        forma = CommentForm()

    data = {'kino': film, 'form': forma, 'comments': comments}
    return render(req, 'catalog/kino_detail.html', data)


class directorlist(generic.ListView):
    model = Director
    paginate_by = 5


class directordetail(generic.DetailView):
    model = Director


class actorlist(generic.ListView):
    model = Actor
    paginate_by = 5


class actordetail(generic.DetailView):
    model = Actor


def reg(req):
    if req.POST:
        f = SignUp(req.POST)
        if f.is_valid():
            f.save()
            k1 = f.cleaned_data.get('username')
            k2 = f.cleaned_data.get('password1')
            k3 = f.cleaned_data.get('email')
            k4 = f.cleaned_data.get('first_name')
            k5 = f.cleaned_data.get('last_name')

            authenticate(username=k1, password=k2)
            newuser = User.objects.get(username=k1)
            newuser.email = k3
            newuser.first_name = k4
            newuser.last_name = k5
            newuser.save()
            ProfiUser.objects.create(user_id=newuser.id, podpiska_id=1)
            login(req, newuser)
            return redirect('home')
    else:
        f = SignUp()
    data = {'forma': f}
    return render(req, 'registration/registration.html', data)


def topodpiska(req, userid):
    data = {}
    if req.POST:
        if req.POST.get('stype'):
            stype = req.POST.get('stype')
            user = User.objects.get(id=userid)
            newpodp = Podpiska.objects.get(level=stype)
            if stype == 'free':
                user.profiuser.podpiska = newpodp

            elif stype == 'based' and user.profiuser.balance >= 1:
                user.profiuser.balance -= 1
                user.profiuser.podpiska = newpodp

            elif stype == 'super' and user.profiuser.balance >= 5:
                user.profiuser.balance -= 5
                user.profiuser.podpiska = newpodp
            user.profiuser.save()

        elif req.POST.get('summa'):
            summa = req.POST.get('summa')
            print(summa)
            user = User.objects.get(id=userid)
            user.profiuser.balance += int(summa)
            user.profiuser.save()
    return render(req, 'podpiska.html', data)

# def plusbalance(req):
#     data = {}
#     return render(req, 'podpiska.html', data)


from django.shortcuts import render, redirect
from .models import *

def search_films(request):
    query = request.GET.get('query')
    if query:
        films = Kino.objects.filter(title__icontains=query)
    else:
        films = []
    return render(request, 'search.html', {'films': films})

templates/catalog/actor_detail.html
{% extends 'index.html' %}
{% load static %}
{% block head %}
    <title>Про режиссёра</title>
    <link rel="stylesheet" href="{% static 'kino_details.css' %}">
{% endblock head %}

{% block content %}
    <ul>
        <li>
            <img src="{{ actor.image }}" alt="{{ actor.name }}">
            <div>
                <h4>Актёр: {{ actor.name }}</h4>
                <h4>Дата рождения: {{ actor.data }}</h4>
                <h4>Количество фильмов: {{ actor.filmcount }}</h4>
                <h4>Лучшие фильмы: {{ actor.best|linebreaks }}</h4>
                <h4>Ссылка: <a href=" {{ actor.info }}">{{ actor.info }}</a></h4>
            </div>
        </li>
    </ul>
{% endblock content %}

templates/catalog/actor_list.html
{% extends 'index.html' %}
{% load static %}
{% block head %}
    <title>Список актёров</title>
    <link rel="stylesheet" href="{% static 'kino_list.css' %}">
{% endblock head %}
{% block content %}
    <h2>Список</h2>
    <ul>
        {% for one in actor_list %}
            <li>
                <img src="{{ one.image }}" alt="{{ one.name }}">
                <div>
                    <a href="{{ one.getAbsUrl }}" class="movie-title">Актёр: {{ one.name }}</a>
              </div>
            </li>
        {% endfor %}
    </ul>
{% if is_paginated %}
<div class="pagination">
<span class="step-links">
        {% if page_obj.has_previous %}
{#            <a href="?page=1">&laquo; first</a>#}
<a href="?page={{ page_obj.previous_page_number }}">пред</a>
        {% endif %}

        <span class="current">
            Стр {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
</span>

        {% if page_obj.has_next %}
<a href="?page={{ page_obj.next_page_number }}">след</a>
{#            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>#}
        {% endif %}
</span>
</div>
{% endif %}
{% endblock content %}

templates/catalog/director_detail.html
{% extends 'index.html' %}
{% load static %}
{% block head %}
    <title>Про режиссёра</title>
    <link rel="stylesheet" href="{% static 'kino_details.css' %}">
{% endblock head %}

{% block content %}
    <ul>
        <li>
            <img src="{{ director.image }}" alt="{{ director.name }}">
            <div>
                <h2>Режисёр: {{ director.name }}</h2>
                <h4>Дата рождения: {{ director.data }}</h4>
                <h4>Количество фильмов: {{ director.filmcount }}</h4>
                <h4>Лучшие фильмы: {{ director.best|linebreaks }}</h4>
                <h4>Ссылка: <a href=" {{ director.info }}">{{ director.info }}</a></h4>


{#                <h4>Комментарии:</h4>#}
{#                {% for comment in kino.get_comments %}#}
{#                    <p>{{ comment.content }}</p>#}
{#                    <small>Автор: {{ comment.user }}</small>#}
{#                    <small>Дата: {{ comment.created_at }}</small>#}
{#                    <hr>#}
{#                {% empty %}#}
{#                    <p>Комментариев пока нет.</p>#}
{#                {% endfor %}#}
{##}
{#                <!-- Форма для добавления нового комментария -->#}
{#                <h4>Оставьте комментарий:</h4>#}
{#                <form action="{% url '#' kino.id %}" method="POST">#}
{#                    {% csrf_token %}#}
{#                    <label>#}
{#                        <textarea name="content" required></textarea>#}
{#                    </label>#}
{#                    <button type="submit">Отправить</button>#}
{#                </form>#}
            </div>
        </li>
    </ul>
{% endblock content %}

templates/catalog/director_list.html
{% extends 'index.html' %}
{% load static %}
{% block head %}
    <title>Список режисеров</title>
    <link rel="stylesheet" href="{% static 'kino_list.css' %}">
{% endblock head %}
{% block content %}
    <h2>Список</h2>
    <ul>
        {% for one in director_list %}
            <li>
                <img src="{{ one.image }}" alt="{{ one.name }}">
                <div>
                    <a href="{{ one.getAbsUrl }}" class="movie-title">Режисёр: {{ one.name }}</a>
              </div>
            </li>
        {% endfor %}
    </ul>
{% if is_paginated %}
<div class="pagination">
<span class="step-links">
        {% if page_obj.has_previous %}
{#            <a href="?page=1">&laquo; first</a>#}
<a href="?page={{ page_obj.previous_page_number }}">пред</a>
        {% endif %}

        <span class="current">
            Стр {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
</span>

        {% if page_obj.has_next %}
<a href="?page={{ page_obj.next_page_number }}">след</a>
{#            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>#}
        {% endif %}
</span>
</div>
{% endif %}
{% endblock content %}

templates/catalog/kino_detail.html
{% extends 'index.html' %}
{% load static %}
{% block head %}
    <title>Про фильм</title>
    <link rel="stylesheet" href="{% static 'kino_details.css' %}">
{% endblock head %}
{% block content %}
    <ul>
        <li>
            <img src="{{ kino.image }}" alt="{{ kino.title }}">
            <div>
                <h2>Фильм: {{ kino.title }}</h2>
                <h4>Режисёр: {{ kino.director }}</h4>
                <h4>Актёры: {{ kino.displayAct }}</h4>
                <h4>Описание: {{ kino.opisanie }}</h4>
                <h4>Подписка: {{ kino.podpiska.get_level_display }}</h4>
                {{ user }}
                {{ user.profiuser.podpiska.id }}
                {{ kino.podpiska.id }}

                {% if user.profiuser.podpiska.id >= kino.podpiska.id %}
                    <iframe width="560" height="315" src="{{ kino.trailer_url }}"
                            frameborder="0" allow="accelerometer; autoplay;
                         clipboard-write; encrypted-media; gyroscope;
                          picture-in-picture; web-share" allowfullscreen></iframe>
                    <a href="{{ kino.poster }}"><h4>Постер: {{ kino.poster }}</h4></a>
                    <form action="" method="post">
                        {% csrf_token %}
                        {{ form }}
                        <input type="submit" value="Отправить">
                    </form>

                    {% for one in comments %}
                        <div class="comment">
                            <span class="username">{{ one.user.username }}</span>
                            <span class="date">{{ one.timedata }}</span>
                            <div class="descriptiomo-nalonvevons">{{ one.body }}</div>
                        </div>
                    {% endfor %}

                    {% if new_comments %}
                        <h3>Новые комментарии:</h3>
                        {% for comment in new_comments %}
                            <div class="comment new-comment">
                                <span class="username">{{ comment.user.username }}</span>
                                <span class="date">{{ comment.timedata }}</span>
                                <p class="body">{{ comment.body }}</p>
                            </div>
                        {% endfor %}
                    {% endif %}

                {% else %}
                    <h3>Купите подписку</h3>
                {% endif %}

            </div>
        </li>
    </ul>
{% endblock content %}

templates/catalog/kino_list.html
{% extends 'index.html' %}
{% load static %}
{% block head %}
    <title>Список фильмов</title>
    <link rel="stylesheet" href="{% static 'kino_list.css' %}">
{% endblock head %}
{% block content %}
    <h2>Каталог</h2>
    <ul>
        {% for one in kino_list %}
            <li>
                <a href="{{ one.getAbsUrl }}">
                    <img src="{{ one.image }}" alt="{{ one.title }}">
                    <div>
                        <p class="movie-title">Фильм: {{ one.title }}</p>
                        <p class="movie-details">Страна: <span>{{ one.country }}</span></p>
                        <p class="movie-details">Год: <span>{{ one.year }}</span></p>


                    </div>
                </a>
            </li>
        {% endfor %}

    </ul>
    {% if is_paginated %}
        <div class="pagination">
<span class="step-links">
        {% if page_obj.has_previous %}
            {#            <a href="?page=1">&laquo; first</a>#}
            <a href="?page={{ page_obj.previous_page_number }}">пред</a>
        {% endif %}

    <span class="current">
            Стр {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
</span>
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">след</a>
        {#            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>#}
    {% endif %}
</span>
        </div>
    {% endif %}

{% endblock content %}